### ISSUE TITLE
Better locate and refer to instructions for running the tests in known containers

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3-conformance-framework#89]
[This directory](https://github.com/finos/FDC3-conformance-framework/tree/main/mock/fdc3-app-config-examples) (_mock/fdc3-app-config-examples_), currently containing a Finsemble config example, probably should not live under the 'mock' directory. Rather it should move up a level and be referred to from the README. 

Both the README file and these examples should be deployed with the framework (copied into the same location as the app builds) so that they can be referenced from the deployed location. Internal links from the README to the examples should use relative paths to ensure that these work post-deployment.

**Comment by robmoffat** [comment]
we just have the `directories` containing config examples, which is referred to in the README.

I don't know if it makes sense to copy the examples into the `dist` and serve them up: they would be no good when deployed on https://directory.fdc3.finos.org, since they all refer to locally-running apps.  Since they only work when running from localhost, this would just be another location to refer to the same files from?
